# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xr < Formula
  desc "xr - manage multiple git repositories"
  homepage "https://github.com/kohbis/xr"
  version "0.0.20"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kohbis/xr/releases/download/v0.0.20/xr_darwin_amd64.tar.gz"
      sha256 "ba4099a8739fbd287936047d1b4bd33e82f7e912dd35d0b713de5630196829ee"

      define_method(:install) do
        bin.install "xr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kohbis/xr/releases/download/v0.0.20/xr_darwin_arm64.tar.gz"
      sha256 "a4f3b20a0a739fee0e7e3ab2317a04d9b1e1804401d3299df939db5e4957d0ab"

      define_method(:install) do
        bin.install "xr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kohbis/xr/releases/download/v0.0.20/xr_linux_amd64.tar.gz"
      sha256 "0ef6abd9c3d81a45ac4cc903a54e6238c1274476c401796706e86d68740be96d"
      define_method(:install) do
        bin.install "xr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kohbis/xr/releases/download/v0.0.20/xr_linux_arm64.tar.gz"
      sha256 "8bfba186bb112698819fa3522186ad75c9fa3c3369627a8a0f4bf7cfec806422"
      define_method(:install) do
        bin.install "xr"
      end
    end
  end

  test do
    system "#{bin}/xr --help"
  end
end
