# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xr < Formula
  desc "xr - manage multiple git repositories"
  homepage "https://github.com/kohbis/xr"
  version "0.0.34"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kohbis/xr/releases/download/v0.0.34/xr_darwin_amd64.tar.gz"
      sha256 "e6694d351923c076e72d3655210c32c725da18c200dd25710c3c4f4b4a226fcb"

      define_method(:install) do
        bin.install "xr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kohbis/xr/releases/download/v0.0.34/xr_darwin_arm64.tar.gz"
      sha256 "a21d01961393e40b984381057de552553a435fca7ad0e410378f521e915c74e9"

      define_method(:install) do
        bin.install "xr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kohbis/xr/releases/download/v0.0.34/xr_linux_amd64.tar.gz"
      sha256 "d25d288bdd597d723e54ff585c023a7348c71358821132d90f0be9342bbb596b"
      define_method(:install) do
        bin.install "xr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kohbis/xr/releases/download/v0.0.34/xr_linux_arm64.tar.gz"
      sha256 "42b763be4cccb608cdfcc3689e3c1d8c31c45745df92e3c033cda66b4867c971"
      define_method(:install) do
        bin.install "xr"
      end
    end
  end

  test do
    system "#{bin}/xr --help"
  end
end
