# This file was generated by GoReleaser. DO NOT EDIT.
cask "xr" do
  name "xr"
  desc "xr - manage multiple git repositories"
  homepage "https://github.com/kohbis/xr"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xr"

  on_macos do
    on_intel do
      url "https://github.com/kohbis/xr/releases/download/v#{version}/xr_darwin_amd64.tar.gz"
      sha256 "f0378013ed6670425b574b4e2a670a700c9108528629288846737e895c108f23"
    end
    on_arm do
      url "https://github.com/kohbis/xr/releases/download/v#{version}/xr_darwin_arm64.tar.gz"
      sha256 "409c5ce38357bfab8c56c7976d9df9e9e4fc799bb71d2c5c81572383ebf34016"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kohbis/xr/releases/download/v#{version}/xr_linux_amd64.tar.gz"
      sha256 "801c1f2b6930a4fda6e660d1c1975a6ac861bd05182676af712e79fe869b9011"
    end
    on_arm do
      url "https://github.com/kohbis/xr/releases/download/v#{version}/xr_linux_arm64.tar.gz"
      sha256 "220b30b41f0f24641db65115519ef788a62ca378aaf3714001a9e89bbb00eb19"
    end
  end

  # No zap stanza required
end
